# Generated by Django 6.0.1 on 2026-01-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição da Vaga')),
                ('requisitos', models.TextField()),
                ('beneficios', models.TextField(blank=True)),
                ('area', models.CharField(max_length=100, verbose_name='Área/Curso')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('estagio', 'Estágio'), ('clt', 'Efetivo/CLT'), ('pj', 'PJ')], default='estagio', max_length=20)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bolsa/Salário')),
                ('prazo_candidatura', models.DateField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='usuarios.perfilempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('carta_apresentacao', models.TextField(blank=True, null=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_candidaturas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'estudante')},
            },
        ),
    ]
