# Generated by Django 6.0.1 on 2026-01-27 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='tipo_contrato',
        ),
    ]
