# Generated by Django 6.0.1 on 2026-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_remove_vaga_tipo_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='ativa',
        ),
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('analise', 'Em Análise'), ('finalizada', 'Finalizada/Preenchida')], default='ativa', max_length=20),
        ),
    ]
