# Generated by Django 6.0.1 on 2026-01-26 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, verbose_name='Sobre a Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição de Ensino')),
                ('curso', models.CharField(max_length=100)),
                ('semestre', models.PositiveIntegerField(default=1)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('habilidades', models.TextField(blank=True, help_text='Liste suas habilidades separadas por vírgula')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
