# Generated by Django 6.0.1 on 2026-01-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudante',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
