# Generated by Django 6.0.1 on 2026-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilestudante_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudantes/'),
        ),
    ]
